added-analytics-cards
lumos-studio/leeway-website pull request #118
Opened 2023-07-14 08:31 UTC by Adhithyarajan

2023-07-14 09:53 UTC, anjali9265 requested changes
@Adhithyarajan I see that you have inserted the image as such but that's not what we want.  If you see in the design we can add the transactions and based on that we calculate the mileage. The card we are implementing right now is to show that calculated mileage. For now, you don't need to think about calculation, just research and implement a card with the style shown in the design where you can display text. You can search for how to add a card in HTML online and make changes afterward.

2023-07-14 20:27 UTC, ajayesivan requested changes

2023-07-14 20:27 UTC, ajayesivan commented on public/images/cards.png
Please remove this image.

2023-07-14 20:27 UTC, ajayesivan commented on public/index.html
> +            </div>
Please format the code. You can enable auto-formatting on save: https://stackoverflow.com/a/54665086/5780058

2023-07-14 20:27 UTC, ajayesivan commented on public/index.html
> +            </div>
Indenting code properly will significantly improve code readability.

2023-07-14 20:27 UTC, ajayesivan commented on public/styles.css
> +  padding: 59px 22px 67px 20px;
Please avoid directly copying code from Figma without considering the underlying reasoning for those styles. Figma-generated styles are specific to the designer's visual representation and may not align with the ideal implementation in code. Instead, let's approach it from a functional perspective. In this case, we need a square container with rounded edges, containing vertically and horizontally centered text with a gradient background. Please try to write the minimum required code to achieve this from scratch. If you require any assistance in better, feel free to reach out.

2023-07-14 20:27 UTC, ajayesivan commented on public/styles.css
> +.card h2 {
It would be beneficial to add class names instead of directly selecting a tag for styling. This approach ensures that even if we decide to change the tag in the future, the style will still apply without requiring updates to the selector. By using class names, we maintain a separation between the structure and style, allowing for more flexibility and easier maintenance.

2023-07-14 20:27 UTC, ajayesivan commented on public/styles.css
> +.card h6 {
Same here.

2023-07-14 20:27 UTC, ajayesivan commented on public/styles.css
> +  color: #FFF;
Define a css variable and use that instead of hardcoding the color directly.

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2023-07-14 20:27 UTC, ajayesivan commented on public/index.html
> +            <div class="card">
It would be better to use more descriptive names instead of generic names like `card` and `card1`. This helps improve code readability and makes it easier to understand the purpose of each card. For example, you can use names like `left-card` and `right-card` to indicate their respective positions.

2023-07-14 20:27 UTC, ajayesivan commented on public/index.html
> +            <div class="card">
Naming classes in CSS can be tricky. I strongly recommend exploring the BEM (Block, Element, Modifier) methodology as it provides a structured approach for naming classes. It can help improve code organization and maintainability. You can learn more about BEM at https://getbem.com/.

2023-07-14 20:30 UTC, ajayesivan commented
In the PR title, you don't have to use `-` to separate words instead, you can use space.

instead of `added-analytics-cards` use `Added analytics cards`.

The same thing applies to commit messages.

2023-07-17 16:33 UTC, ajayesivan requested changes

2023-07-17 16:33 UTC, ajayesivan commented on public/styles.css
> +:root {
We already have multiple `:root` selectors. To avoid redundancy, combine all the variable declarations under a single `:root` selector.

2023-07-17 16:33 UTC, ajayesivan commented on public/styles.css
> +} */
Please remove commented code.

2023-07-20 07:39 UTC, ajayesivan approved these changes

2023-07-20 09:09 UTC, Adhithyarajan commented
The squash and merge option is not active here. Why ?

2023-07-20 09:22 UTC, ajayesivan approved these changes

2023-07-20 09:22 UTC, ajayesivan approved these changes

2023-07-20 10:08 UTC, ajayesivan commented on public/styles.css
> +  margin-bottom: 50px;
Please use flex to center elements and remove the margins.

2023-07-20 10:09 UTC, ajayesivan requested changes
There are multiple places where you are using margin to align elements, please take advantage of CSS Flexbox to it and avoid using random margin values.

2023-07-20 12:01 UTC, anjali9265 reviewed
@Adhithyarajan please use relative units instead of px. This ensures that our designs work in all screen dimensions.

2023-07-20 14:48 UTC, ajayesivan commented on public/styles.css
> +  height: 25%;
I think for cards we can use `px` values. @anjali9265 wdyt?

2023-07-20 14:51 UTC, ajayesivan commented on public/styles.css
> +  text-indent: -50%;
I don't think this is the right way to fix it. Can you find a solution without using `text-indent` property?

2023-07-20 14:52 UTC, ajayesivan commented on public/styles.css
> +  height: 25%;
Also, the right card dimensions.

2023-07-20 14:53 UTC, ajayesivan commented on public/styles.css
> +  padding: 0px 7px 12px 25px;
Any reason for using padding like this?

2023-07-20 14:53 UTC, ajayesivan commented on public/styles.css
> +  margin-top: 19px;
Try to achieve the result without using margins

2023-07-20 16:43 UTC, anjali9265 commented on public/styles.css
> +  height: 25%;
Cards could use px. I think I saw margin and padding using px values, preferably we can change that.

2023-07-20 17:42 UTC, Adhithyarajan commented on public/styles.css
> +  font-size: 1.7em;
Just because it is a relative unit.

2023-07-20 17:43 UTC, Adhithyarajan commented on public/styles.css
> +  padding: 0px 7px 12px 25px;
Copied from figma initially, then I think I had changed the values.

2023-07-21 02:42 UTC, ajayesivan commented on public/styles.css
> +  font-size: 1.7em;
😅. Then I don't recommend using it here. `em` depends on the parent element size and will give you unexpected results if you are using it without properly understanding it. Please change it back to `px`. Also, spend some time learning how `rem` & `em` units work and their usecases.

2023-07-21 02:47 UTC, ajayesivan commented on public/styles.css
> +  padding: 0px 7px 12px 25px;
You should understand why you are writing a line of code. If you don't have a reason for adding this line then remove it.

2023-07-21 07:23 UTC, ajayesivan commented on public/styles.css
> +  margin-left: -37%;
Using margin-left is not the ideal solution. This implementation will result in alignment issues when the value changes, check the screenshot below

<img width="277" alt="Screenshot 2023-07-21 at 12 49 59" src="https://github.com/lumos-studio/leeway-website/assets/19279756/c304b628-ba9e-444c-8552-6dfb20e1633d">

Try to come up with a solution that doesn't involve margin and works even if the millage value changes.

2023-07-21 07:25 UTC, ajayesivan commented on public/styles.css
> +  width: 65px;
The right card is a square. `width` & `height` should be equal.

2023-07-21 07:27 UTC, ajayesivan commented on public/styles.css
> +  padding: 20%;
What is the reason for adding 20% padding?

2023-07-21 07:49 UTC, Adhithyarajan commented on public/styles.css
> +  padding: 20%;
To achieve a padding for all sides.

2023-07-21 08:32 UTC, ajayesivan commented on public/styles.css
> +  padding-right: 40%;
Changing from margin to padding won't cut it. To get the correct solution you may need to change the HTML structure. CSS alone won't always get you the right results, sometimes you may have to tweak your HTML along with CSS to get the correct result. If you need help let me know.

2023-07-21 08:34 UTC, ajayesivan commented on public/styles.css
> +  padding: 20%;
Okay, then why are you only using padding for right-card? The left-card doesn't have any padding at all, is there any reason for that?

2023-07-21 09:40 UTC, Adhithyarajan commented on public/styles.css
> +  padding: 20%;
Left card is already looking fine

2023-07-21 09:40 UTC, Adhithyarajan commented on public/styles.css
> +  padding-right: 40%;
Yes. I need help.

2023-07-21 13:34 UTC, ajayesivan commented on public/styles.css
> +  padding: 20%;
Looking fine with the current data is not good enough. I have copied the minimum code from your implementation to a codepen to show you the issue and how to fix it by editing the HTML structure. Please check,

Your implementation: https://codepen.io/Ajay-Sivan/pen/VwVBwPN
With the fix: https://codepen.io/Ajay-Sivan/pen/MWzBWpO

2023-07-21 13:40 UTC, ajayesivan commented on public/styles.css
> +  padding-right: 40%;
I have copied the minimum code from your implementation to a codepen to show you the issue and how to fix it by editing the HTML structure. Please check,

Your implementation: https://codepen.io/Ajay-Sivan/pen/VwVBwPN
With the fix: https://codepen.io/Ajay-Sivan/pen/MWzBWpO

2023-07-21 13:43 UTC, ajayesivan commented on public/styles.css
> +  padding: 20%;
I agree with you. But since you have been coding with HTML & CSS for over a month you need to start understanding why it looks that way.

2023-07-21 14:24 UTC, ajayesivan approved these changes

2023-07-21 14:41 UTC, Adhithyarajan commented on public/styles.css
> +  padding: 0px 7px 12px 25px;
I think it is because of the flex property i've added on that card.

2023-07-21 14:42 UTC, Adhithyarajan commented on public/styles.css
> +  padding: 20%;
i think it is because of the flex property i've added on that.

2023-07-21 14:50 UTC, Adhithyarajan commented
Still the squash and merge option is not active.

2023-07-21 15:17 UTC, ajayesivan commented
> Still the squash and merge option is not active.

We need approval from @anjali9265 to merge. She will review it later today.

2023-07-23 14:16 UTC, ajayesivan approved these changes

2023-07-24 08:12 UTC, anjali9265 approved these changes

2023-07-24 12:11 UTC, merged